@startuml

class 720特大暴雨 {
  应急案例
  ---
  影响范围：河南省 150 个县（市、区）
  受灾人口：1478.6 万人
  直接经济损失：1200.6 亿元
}

class 郑州 {
  应急案例客体
  ---
  地理位置
  中心人口
}


class 暴雨过程 {
  事件发展
  ---
}

class 初始情景 {
  情景
  ---
  发生时间: 17 日至 18 日
  客体: 豫北
}

class 结束情景 {
  情景
  ---
  发生时间：21 日至 22 日
  内容：暴雨中心再次北移，逐渐减弱结束
}

class 过程情景 {
  情景
}

class 过程情景1 {
  情景
  ---
  客体：郑州
  内容：过程累计面雨量534mm
}

class 过程情景2 {
  情景
  ---
  客体：鹤壁
  内容：过程累计面雨量589mm
}

class 过程情景3 {
  情景
  ---
  客体：新乡
  内容：过程累计面雨量512mm
}

class 过程情景4 {
  情景
  ---
  客体：鹤壁科创中心气象站
  内容：过程点雨量1122.6mm
}

class 过程情景5 {
  情景
  ---
  客体：郑州新密市白寨气象站
  内容：过程点雨量993.1mm
}

class 过程情景6 {
  情景
  ---
  客体：郑州
  时间：20 日16 时至17 时
  内容：小时最强点雨量201.9mm
}

class 过程情景7 {
  情景
  ---
  客体：鹤壁
  时间：21 日14 时至15 时
  内容：小时最强点雨量120.5mm
}

class 过程情景8 {
  情景
  ---
  客体：新乡
  时间：21日20时至17时
  内容：小时最强点雨量114.7mm
}

暴雨过程 --> 初始情景 : 伴随
暴雨过程 --> 过程情景 : 伴随
暴雨过程 --> 结束情景 : 伴随
过程情景 --> 过程情景1 : 子过程
过程情景 --> 过程情景2 : 子过程
过程情景 --> 过程情景3 : 子过程
过程情景 --> 过程情景4 : 子过程
过程情景 --> 过程情景5 : 子过程
过程情景 --> 过程情景6 : 子过程
过程情景 --> 过程情景7 : 子过程
过程情景 --> 过程情景8 : 子过程


class 暴雨应急体系 {
  应急案例主体
  ---
}

class 应急管理部 {
  政府组织
  ---
}

class 发展改革委 {
  政府组织
  ---
}

class 财政部 {
  政府组织
  ---
}

class 水利部 {
  政府组织
  ---
}

class 国务院 {
  政府组织
  ---
}





暴雨应急体系 --> 应急管理部
暴雨应急体系 --> 发展改革委
暴雨应急体系 --> 财政部
暴雨应急体系 --> 水利部
暴雨应急体系 --> 国务院

class 事件处置 {
  事件处置
  ---
}

class 灾害处置 {
  应急处置过程
  ---
}

事件处置 --> 灾害处置

class 应急恢复 {
  应急恢复过程
  ---
}

class 组织 {
  动作
  ---
  内容：开展灾害损失综合评估和灾害范围评估
}

class 汇同 {
  动作
  ---
  客体：发展改革委、财政部、水利部
  内容：上报国务院
}

class 编制 {
  动作
  ---
  客体：河南省编制灾后恢复重建规划
}

事件处置 --> 应急恢复
组织 --> 应急管理部 : 主体
汇同 --> 应急管理部 : 主体
编制 --> 国务院 : 主体
组织 --> 应急恢复 : 组成
汇同 --> 应急恢复 : 组成
编制 --> 应急恢复 : 组成

720特大暴雨 --> 事件处置


720特大暴雨 --> 郑州
720特大暴雨 --> 暴雨过程
720特大暴雨 --> 暴雨应急体系

@enduml